import { Inter } from 'next/font/google';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Header from '@/components/header/header';
import ReduxProvider from '@/components/reduxProvider/reduxProvider';
import FooterWrapper from '@/components/footerWrapper/footerWrapper';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://pro.fontawesome.com/releases/v5.11.2/css/all.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        />

        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
        ></link>
        <script
          async
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        ></script>
        <script
          async
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        ></script>
        {/* <script src="https://d3js.org/d3.v7.min.js"></script> */}
      </head>
      <body className={inter.className}>
        <ReduxProvider>
          <Header></Header>
          {/* <SessionCheck></SessionCheck> */}
        </ReduxProvider>
        <div id="page-holder">{children}</div>
        <FooterWrapper></FooterWrapper>
        <ToastContainer></ToastContainer>
      </body>
    </html>
  );
}
